services:
  worker:
    build: .
    command: python -u -m app.services.worker_rmq
    environment:
      PYTHONUNBUFFERED: "1"
      RABBITMQ_URL: ${RABBITMQ_URL}
      RMQ_EXCHANGE: bridge
      RMQ_TASK_QUEUE: bridge.tasks
      RMQ_RETRY_QUEUE: bridge.tasks.retry
      RMQ_RETRY_TTL_MS: 5000

      DATABASE_URL: ${DATABASE_URL}

      AMO_BASE_URL: ${AMO_BASE_URL}
      AMO_CLIENT_ID: ${AMO_CLIENT_ID}
      AMO_CLIENT_SECRET: ${AMO_CLIENT_SECRET}
      AMO_REDIRECT_URI: ${AMO_REDIRECT_URI}
      HH_USER_AGENT: ${HH_USER_AGENT}


      AMO_CHATS_SCOPE_ID: ${AMO_CHATS_SCOPE_ID}
      AMO_CHATS_SECRET: ${AMO_CHATS_SECRET}
      AMO_CHATS_CHANNEL_ID: ${AMO_CHATS_CHANNEL_ID}
      AMO_CHATS_ACCOUNT_ID: ${AMO_CHATS_ACCOUNT_ID}
      AMO_CHATS_SENDER_USER_AMOJO_ID: ${AMO_CHATS_SENDER_USER_AMOJO_ID}

    restart: unless-stopped


