"""init tables

Revision ID: 9c2466183e7f
Revises: 
Create Date: 2025-08-20 19:53:38.419280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2466183e7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_dedup',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_events_dedup_created_at'), 'events_dedup', ['created_at'], unique=False)
    op.create_table('lead_links',
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=True),
    sa.Column('vacancy_id', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('tg_links',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_kind', sa.Text(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'bot_kind')
    )
    op.create_index(op.f('ix_tg_links_lead_id'), 'tg_links', ['lead_id'], unique=False)
    op.create_table('tg_surveys',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_kind', sa.Text(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('time_pref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'bot_kind')
    )
    op.create_index(op.f('ix_tg_surveys_lead_id'), 'tg_surveys', ['lead_id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service', 'owner_id', name='ux_tokens_service_owner')
    )
    op.create_index(op.f('ix_tokens_owner_id'), 'tokens', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tokens_service'), 'tokens', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_service'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_owner_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_tg_surveys_lead_id'), table_name='tg_surveys')
    op.drop_table('tg_surveys')
    op.drop_index(op.f('ix_tg_links_lead_id'), table_name='tg_links')
    op.drop_table('tg_links')
    op.drop_table('lead_links')
    op.drop_index(op.f('ix_events_dedup_created_at'), table_name='events_dedup')
    op.drop_table('events_dedup')
    # ### end Alembic commands ###
